### ISSUE TITLE
Duplication of classes

### ISSUE THREAD

**Issue by hisbvdis** [solnurkarim/HTML-to-CSS-autocompletion#3]
When some class is attend in source html-file and current css-file, it leads to duplication of items on autocomplete panel.

Is it possible to configure to avoid this duplication?
Thanks

![Screenshot](https://monosnap.com/image/yghYu7GzeLZ6Mezh0CZ27JyRhqM8Fd.png)

**Comment by solnurkarim** [comment]
VSCode provides it's own selector suggestions list within CSS language provider. The issue is they do not provide API neither to filter their list of suggestions nor to read it and filter extension's list. As far as I know currently it's not possible to do it in an 'expected' way through provided APIs.

**Comment by hisbvdis** [comment]
> VSCode provides it's own selector suggestions list within CSS language provider. The issue is they do not provide API neither to filter their list of suggestions nor to read it and filter extension's list. As far as I know currently it's not possible to do it in an 'expected' way through provided APIs.

That's too bad.
Thanks for the reply

**Comment by ahnor75802** [comment]
vs code only shows classes & ids selectors when they are written in file you are in (more like local suggestion based on what you typed), so can you consider add button to disable your provide of the suggestion when there is already the class or the id in the current file (as vscode would suggest it himself)
